version: 2
models:
  - name: stg_stations
    columns:
      - name: ID
        tests:
          - not_null
          - unique
  - name: stg_weekday
    columns:
      - name: ID
        tests:
          - not_null
  - name: stg_richards
    columns:
      - name: timestamp
        tests:
          - not_null